subscriptionIDs:
  - "67a16f0f-e2c3-4cc4-a17d-c9e4e2a0e8c1"
  - "a4225384-b567-4381-9ca4-13f5e2e5ab6c"
ignoreResourceIDPatterns:
  - "resourceGroups/Default-ActivityLogAlerts"
  - "resourceGroups/NetworkWatcherRG"
  - "Microsoft.OperationsManagement/solutions/ChangeTracking"
  - "Microsoft.OperationsManagement/solutions/SecurityInsights"
ignoreResourceTypePatterns:
  - "random_uuid.telemetry"
  - "modtm"
  - "module.management_groups"
  - "bastion"
  - "dns_resolver"
  - "azurerm_route"
  - "azurerm_route_table"
  - "module.private_dns_zone_auto_registration"
resourceGraphQueries:
  - name: "Resource Groups"
    query: |
      resourcecontainers
      | where type == "microsoft.resources/subscriptions/resourcegroups"
      | project id, name, type, location, subscriptionId, resourceGroup = name
  - name: "Top Level Resources"
    query: |
      resources
      | project name, id, type, location, subscriptionId, resourceGroup
  - name: "Virtual Network Subnets"
    query: |
      resources
      | where type == "microsoft.network/virtualnetworks"
      | project id, name, type, location, subscriptionId, resourceGroup, subnets = properties.subnets
      | mv-expand subnets
      | project name = tostring(subnets.name), id = tostring(subnets.id), type = tostring(subnets.type), location, subscriptionId, resourceGroup
  - name: "Virtual Network Peerings"
    query: |
      resources
      | where type == "microsoft.network/virtualnetworks"
      | project id, name, type, location, subscriptionId, resourceGroup, peerings = properties.virtualNetworkPeerings
      | mv-expand peerings
      | project name = tostring(peerings.name), id = tostring(peerings.id), type = tostring(peerings.type), location, subscriptionId, resourceGroup
nameFormats:
  - type: azurerm_log_analytics_solution
    nameFormat: "%s(%s)"
    nameMatchType: Exact
    nameFormatArguments:
      - solution_name
      - workspace_name
  - type: azurerm_private_dns_zone_virtual_network_link
    nameFormat: "providers/Microsoft.Network/privateDnsZones/%s/virtualNetworkLinks/%s"
    nameMatchType: IDContains
    nameFormatArguments:
      - private_dns_zone_name
      - name
