name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest
        go test -json ./... | go-ctrf-json-reporter -output ctrf-report.json

    - name: Publish Test Report
      uses: ctrf-io/github-test-reporter@v1
      with:
        report-path: './ctrf-report.json'
        pull-request-report: true
        summary-report: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()